pipeline {
    agent any

    environment {
        NAME = 'plankton'
        DOCKERFILE_PATH = './Plankton.App/Dockerfile'
    }

    stages {
        stage('Build Podman Image') {
            steps {
                echo "🛠️ Building image ${NAME}"
                sh """
                    sudo podman build \
                        --pull \
                        -t ${NAME} \
                        -f ${DOCKERFILE_PATH} .
                """
            }
        }

        stage('Deploy Podman Container') {
            steps {
                withFolderProperties {
                    echo "🚀 Deploying container ${NAME}"
                    sh """
                        if sudo podman ps -a --format '{{.Names}}' | grep -q "^${NAME}\$"; then
                            sudo podman rm -f ${NAME}
                        fi

                        sudo podman run \
                            --network=host \
                            --restart always \
                            --name ${NAME} \
                            -e PLANKTON_BASE_ADDRESS=${env.PLANKTON_BASE_ADDRESS} \
                            -e PLANKTON_HTTP_ID=${env.PLANKTON_HTTP_ID} \
                            -e PLANKTON_TELEGRAM_ID=${env.PLANKTON_TELEGRAM_ID} \
                            -e PLANKTON_TELEGRAM_TOKEN=${env.PLANKTON_TELEGRAM_TOKEN} \
                            -d \
                            ${NAME}
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
    }
}
